swagger: "2.0"
info:
  title: "My API Gateway"
  description: "API Gateway for Django and FastAPI services"
  version: "1.0.0"
paths:
  /api/backend:
    get:
      summary: "Call Django Backend"
      operationId: "djangoBackend"
      x-google-backend:
        address: "http://127.0.0.1:8000/"
      responses:
        "200":
          description: "Success"
  /api/chatbot:
    post:
      summary: "Call FastAPI Chatbot"
      operationId: "fastapiChatbot"
      x-google-backend:
        address: "http://127.0.0.1:3000/"
      responses:
        "200":
          description: "Success"