version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: gdsc_2025/backend:latest
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    image: gdsc_2025/frontend:latest
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  chatbot:
    build:
      context: ./chatbot
    image: gdsc_2025/chatbot:latest
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./chatbot:/app
      - /app/node_modules
