services:
  backend:
    build:
      context: ./backend
    image: dinhtanloc/gdsc_2025/backend:backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    image: dinhtanloc/gdsc_2025/frontend:frontend
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules


  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_name}
      POSTGRES_USER: ${DB_user}
      POSTGRES_PASSWORD: ${DB_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: