langsmith:
  tracing: "true"
  project_name: "chatbot_project"

memory:
  directory: memory



admindata:
  doc_dir: "src/frontend/public/media/documents/admin"
  chunk_size: 500
  chunk_overlap: 100
  db_name: "docpdf"
  collection_name: "rag-admin"

userdata:
  doc_dir: "src/frontend/public/media/documents"
  chunk_size: 500
  chunk_overlap: 100
  db_name: "docpdf"
  collection_name: "rag-docs"