langsmith:
  tracing: "true"
  project_name: "chatbot_project"

memory:
  directory: memory



admindata:
  doc_dir: "frontend/public/media/documents/admin"
  chunk_size: 500
  chunk_overlap: 100
  db_name: "GDSC"
  collection_name: "news"

userdata:
  doc_dir: "frontend/public/media/documents"
  chunk_size: 500
  chunk_overlap: 100
  db_name: "GDSC"
  collection_name: "pdf_report"
